version: "3"
services:
  db:
    image: postgres:latest
    container_name: bigdata_db
    env_file: .env
    volumes:
      - ./.pgSQL/:/var/lib/postgresql/data
    ports:
      - "9843:5432"
    logging:
      driver: json-file
      options:
        max-size: 50m
